steps:
  # Build application image tagged with the commit SHA
  - name: gcr.io/cloud-builders/docker
    id: docker-build
    args: [
      "build",
      "-t",
      "${_REGION}-docker.pkg.dev/${PROJECT_ID}/${_APP_NAME}/${_APP_NAME}:${SHORT_SHA}",
      "app",
    ]

  # Push application image to Artifact Registry
  - name: gcr.io/cloud-builders/docker
    id: docker-push
    args: [
      "push",
      "${_REGION}-docker.pkg.dev/${PROJECT_ID}/${_APP_NAME}/${_APP_NAME}:${SHORT_SHA}",
    ]

  # Deploy Kubernetes manifests to GKE
  - name: gcr.io/cloud-builders/gke-deploy
    id: kubernetes-deploy
    args:
      - "run"
      - "--filename=kubernetes"
      - "--image=${_REGION}-docker.pkg.dev/${PROJECT_ID}/${_APP_NAME}/${_APP_NAME}:${SHORT_SHA}"
      - "--location=${_REGION}"
      - "--cluster=${_GKE_CLUSTER}"

options:
  logging: CLOUD_LOGGING_ONLY

substitutions:
  _REGION: europe-west3
  _APP_NAME: burnout-app
  _GKE_CLUSTER: suml-dev-gke
