name: Kubernetes

on:
  pull_request:
    paths:
      - "kubernetes/**"
      - ".github/workflows/pr-kubernetes.yaml"

permissions:
  contents: read

jobs:
  kubernetes-validate:
    name: Validate manifests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v5

      - name: Validate Kubernetes manifests
        run: |
          docker run --rm \
            --volume "${{ github.workspace }}:/workspace" \
            --workdir /workspace \
            ghcr.io/yannh/kubeconform:v0.7.0 \
            -strict -summary \
            -schema-location default \
            -schema-location 'https://raw.githubusercontent.com/datreeio/CRDs-catalog/main/{{.Group}}/{{.ResourceKind}}_{{.ResourceAPIVersion}}.json' \
            kubernetes
